import React, { useState, ChangeEvent, FormEvent } from 'react';
import { OpenAI } from 'openai';
import reactLogo from './assets/react.svg';
import viteLogo from '/vite.svg';
import './App.css';

export default function App() {
  const [userPrompt, setPrompt] = useState<string>("");
  const [imageUrl, setImageUrl] = useState<string | null>(null);

  const client = new OpenAI({
    apiKey: import.meta.env.VITE_OPENAI_API_KEY,
    dangerouslyAllowBrowser: true,
  });

  async function generateImage(): Promise<string | null> {
    try {
      const response = await client.images.generate({
        prompt: userPrompt,
        model: 'dall-e-3',
        n: 1,
        size: '1024x1024',
      });
      return response.data[0]?.url || null;
    } catch (error) {
      console.error('Error generating image:', error);
      return null;
    }
  }

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    console.log('Submitted prompt:', userPrompt);
    const url = await generateImage();
    if (url) {
      setImageUrl(url);
    }
  };

  return (
    <>
      <div>
        <a href="https://vite.dev" target="_blank" rel="noreferrer">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank" rel="noreferrer">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>

      <h1>DALL·E Proof of Concept</h1>

      <div className="card">
        <form onSubmit={handleSubmit}>
          <input
            type="text"
            placeholder="Type prompt here"
            value={userPrompt}
            onChange={(e: ChangeEvent<HTMLInputElement>) => setPrompt(e.target.value)}
          />
          <button type="submit">Submit</button>
        </form>
      </div>

      {imageUrl && (
        <div className="result">
          <h2>Generated Image</h2>
          <img src={imageUrl} alt="Generated by DALL·E" />
        </div>
      )}

      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  );
}
